language: node_js
node_js:
#  - "0.11" disabled: fibers 1.0.1 doesn't seem to support it
  - "0.10"
  - "0.8"
#  - "0.6" disabled: Needy 0.5.1 doesn't seem to support it
services:
  - couchdb
before_script:
  - node ./test/helpers/seed.js
  
